name: Maha Bali
favicon: null
layout_spectrum: 0.24755
typography_spectrum: 0.7882144125178456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8e9bf'
    - '#ffffff'
    - '#dae5c9'
    - '#e7eeda'
    - '#edf4e4'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
