analytics: {}
color:
  brandColors:
    - '#d8e9bf'
    - '#ffffff'
    - '#dae5c9'
    - '#e7eeda'
    - '#edf4e4'
  brandStrength: 0.193693
  lightness: 1
  rhythmicContrast: 0.493243
  saturation: 0.5
cta: {}
layout_spectrum: 0.208333
name: Maha Bali
opengraph: {}
purpose: []
typography_spectrum: 1
