analytics: {}
color:
  brandColors:
    - '#d8e9bf'
    - '#ffffff'
    - '#dae5c9'
    - '#e7eeda'
    - '#edf4e4'
  brandStrength: 0.1875
  lightness: 1
  rhythmicContrast: 0.244369
  saturation: 0.75
cta: {}
layout_spectrum: 0.75416
name: Maha Bali
opengraph: {}
purpose: []
typography_spectrum: 1
