name: MAHA BALI
favicon: null
layout_spectrum: 0.99902
typography_spectrum: 0.49022
title: 'The Maha Bali Villas | Professional Vacation Rental in Bali'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8e9bf'
    - '#ffffff'
    - '#dae5c9'
    - '#e7eeda'
    - '#edf4e4'
  brandStrength: 0.193693
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.493243
purpose: []
