name: Maha Bali
favicon: null
layout_spectrum: 0.9427000710275024
typography_spectrum: 0.7882144125178456
title: 'The Maha Bali Villas | Professional Vacation Rental in Bali'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#97c3f4'
    - '#191b44'
    - '#ffffff'
    - '#636db2'
    - '#f97000'
  brandStrength: 0.6497309762053192
  lightness: 0.6547223466914147
  saturation: 0.5795350840780884
  rhythmicContrast: 0.25
purpose: []
